# alias
alias v='nvim'
alias s='sudo '
alias ga='git add '
alias gp='git push'
alias gc='git commit -m'
alias conf='cd ~/.config && nvim "$(sk)"'
alias inst='paru -S --skipreview --needed '
alias del='paru -R '
alias aur='sh ~/Scripts/aur.sh'
alias rm='rm -I'
alias ls='ls --color=auto'
